import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import postcss from "postcss";
import tailwind from "@tailwindcss/postcss";
import autoprefixer from "autoprefixer";
import { readFile, writeFile } from "fs/promises";
import { watch as fsWatch } from "fs";
import esbuildSvelte from 'esbuild-svelte';
import { sveltePreprocess } from 'svelte-preprocess';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

async function buildCss() {
	const src = "src/styles/tailwind.css";
	const out = "styles.css";
	try {
		const css = await readFile(src, "utf8");
		const result = await postcss([tailwind, autoprefixer]).process(css, { from: src, to: out });
		await writeFile(out, result.css);
		console.log("tailwind: built styles.css");
	} catch (e) {
		console.error("tailwind: build failed", e);
	}
}

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	plugins: [
    esbuildSvelte({
      compilerOptions: { css: 'injected' },
      preprocess: sveltePreprocess(),
    }),
  ],
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await buildCss();
	process.exit(0);
} else {
	await buildCss();
	await context.watch();
	fsWatch("src/styles/tailwind.css", { persistent: false }, async () => {
		await buildCss();
	});
}
